#!/sbin/sh
# arg 1 is recovery api version, generally 3.
# arg 2 is the pipe fd, to the recovery binary.
# communicate with it using the recovery api.
# arg 3 is the zip file
echo -n -e 'ui_print Installing Superuser...\n' > /proc/self/fd/$2
echo -n -e 'ui_print\n' > /proc/self/fd/$2

# detect binary versions to install
ARCH=$(uname -m)

# x86 needs to match: i486, i686, x86_64, ...
if echo "$ARCH" | grep -q 86; then
  PLATFORM=x86
elif [ "$ARCH" = "mips" -o "$ARCH" = "mips64" ]; then
  PLATFORM=mips
else
  PLATFORM=armeabi
fi

cd /tmp
mkdir superuser
cd superuser
unzip -o "$3"

if [ "$?" -ne "0" ]
then
#Called when updating SU from the app
  mkdir -p $PLATFORM
  cp /cache/su $PLATFORM/su
  cp /cache/Superuser.apk .
  cp /cache/install-recovery.sh .
fi


echo -n -e 'ui_print Installing '$PLATFORM' binaries...\n' > /proc/self/fd/$2
echo -n -e 'ui_print\n' > /proc/self/fd/$2

mount /system
chattr -i /system/bin/su
chattr -i /system/xbin/su
rm -Rf /system/{x,}bin/su /system/app/Super{U,u}ser* /system/app/superuser* /system/app/SuperSU/

cp $PLATFORM/su /system/xbin/su
chown 0:0 /system/xbin/su
chmod 0755 /system/xbin/su

cp Superuser.apk /system/app
chmod 644 /system/app/Superuser.apk

# if the system is at least 4.3, and there is no su daemon built in,
# let's try to install it using install-recovery.sh
BUILD_VERSION_SDK="$(grep 'ro\.build\.version\.sdk' /system/build.prop)"
BUILD_VERSION_SDK="${BUILD_VERSION_SDK##*=}"

if [ "$BUILD_VERSION_SDK" -le 18 ];then
	echo -n -e 'ui_print Sorry, but your Android is too old for me...\n' > /proc/self/fd/$2
	umount /system
	exit 1
fi
if [ -f "/system/etc/.has_su_daemon" ]
	echo -n -e "ui_print Your ROM already has a root, I don't want to override it.\n" > /proc/self/fd/$2
	umount /system
	exit 1
fi

echo -n -e 'ui_print Installing Superuser daemon...\n' > /proc/self/fd/$2
echo -n -e 'ui_print\n' > /proc/self/fd/$2

#TODO: I've also seen install*_*recovery.sh, I thi
for i in etc/install-recovery.sh bin/install-recovery.sh bin/install_recovery.sh;do
	chattr -i /system/$i
	cp install-recovery.sh /system/$i
	chmod 0755 /system/$i
done

#Rename original app_process32
if [ ! -f /system/bin/app_process32.old ];then
	mv /system/bin/app_process32 /system/bin/app_process32.old
fi
cp $PLATFORM/placeholder /system/bin/app_process32
chmod 0755 /system/bin/app_process32
chcon u:object_r:zygote_exec:s0 /system/bin/app_process32

# note that an post install su daemon was installed
# so recovery doesn't freak out and recommend you disable
# the install-recovery.sh execute bit.
touch /system/etc/.installed_su_daemon

umount /system
